include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
